### ISSUE TITLE
Can it be applied to landslides model?

### ISSUE THREAD

**Issue by keepfighting666** [ZeyuJin/geodetic_inversion#10]
I am currently working on a project related to landslide modeling and I am interested in understanding if your code can be adapted for this purpose.
Specifically, I am curious about the following points:
Applicability: Can your fault inversion code be used directly for modeling landslide movements, or would it require significant modifications?
Modifications: If modifications are necessary, could you provide some guidance or suggestions on what aspects of the code would need to be adjusted?
Data Requirements: What type of input data does your code require, and would this be compatible with typical data sets used in landslide studies?

**Comment by x3zou** [comment]
Hi Lijuan,

  Landslide is not my expertise. But if your desired model follows the rule Gu=d, where d is the ground surface deformation (observation), G is the green function of the earth material, and u is the slip (slides?) distribution model, then it is possible to use our code. There also should be an assumption that all the slides occur on a plane, but I'm not sure it fits the actual scenario. As for the input data, our code accepts either InSAR ground deformation and looking angle data, processed by GMTSAR, or GPS (deformation and coordinates) data, or both.

Regards,
Xiaoyu

**Comment by ZeyuJin** [comment]
Hi Lijuan,

The landslide modeling is mainly based on soil and fluid mechanics, which is beyond the scope of theory of elasticity used for the Okada's model. You can refer this paper for the introduction of landslide models: https://dlgeorge.github.io/pubs/IversonGeorge2016_Geotechnique_Oso.pdf

Cheers,
Zeyu
