### ISSUE TITLE
make_insar_data.m

### ISSUE THREAD

**Issue by bad-guyluke** [ZeyuJin/geodetic_inversion#13]
Hello, I would like to know if the mesh file of look_e.grd read using grdread2 in the script make_insar_data.m is processed by a forward script or function? I have gone through gmt grdinfo to get the information about the file and it shows that the file is from lke.grd. But I can not find the lke.grd.And my question is when in the LOS2 folder which GRD files should be prepared.
<img width="979" alt="截屏2024-09-27 16 42 46" src="https://github.com/user-attachments/assets/7220f3ee-eee2-4a6b-9018-3ca5c37753e4">
<img width="707" alt="截屏2024-09-27 16 43 16" src="https://github.com/user-attachments/assets/766185fc-87c3-45ba-a7b5-d7c177de368e">
![截屏2024-09-27 16 47 23](https://github.com/user-attachments/assets/d47a0ac4-27ce-4e3a-87c0-f76765e1705b)

**Comment by x3zou** [comment]
Hello,

 I have uploaded the script (get_look.sh) to generate the looking angle files. Please try that to make the look_e, look_n, look_n GRD files. And please let me know if you have more questions.

Thanks,
Xiaoyu

**Comment by bad-guyluke** [comment]
Hello, 
The problem with look_e.grd has been solved so far. However, in step 5 of make_fault_from_InSAR3.m, a new problem has appeared. In my workexample, the faults are connected to each other, but if I want to define two faults that are basically parallel, how should I go about defining the segment_file.In the following images, the first image is the error message; the second image is the latitude and longitude information of the two faults, and the third image is the content in seg_connect.


<img width="1147" alt="截屏2024-10-01 16 32 36" src="https://github.com/user-attachments/assets/1ddc8227-2a6d-4ff6-bf33-a6f7e27504fc">



<img width="567" alt="截屏2024-10-01 16 33 00" src="https://github.com/user-attachments/assets/96a086f0-27af-4641-a474-3f25b63a8b67">


<img width="241" alt="截屏2024-10-01 16 33 35" src="https://github.com/user-attachments/assets/5d69b577-e094-4c34-8d7d-cc09a9545993">

**Comment by x3zou** [comment]
Hello,

  If your faults are not connected, you can try to set the segment file input to empty '[ ]'
