### ISSUE TITLE
Grid density

### ISSUE THREAD

**Issue by bad-guyluke** [ZeyuJin/geodetic_inversion#14]
hello, I ran through the procedure using other InSAR data, but the grid point densities for the fault slip model don't seem to be the same as inside the Workexample. What parameters do I need to adjust to increase the number of grid points.

<img width="1214" alt="截屏2024-10-09 19 37 41" src="https://github.com/user-attachments/assets/1ea37611-d100-4dbb-915a-71891fab8e64">

**Comment by x3zou** [comment]
Hello,

You can modify the number of fault patches by changing the input parameters for **load_fault_one_plane()**
To increase the number of fault patches, you can try to reduce the len_top, l_ratio, w_ratio, or increase the N_layer. You can play with those parameters until you get a satisfactory number of fault patches.

Thanks,
Xiaoyu

**Comment by bad-guyluke** [comment]
Hello,
Thank you very much for your patience and guidance. Regarding the grid point density I think I have figured out how to adjust it. But I have another question, can I adjust the fault parameters to make the dip of the fault vary with the depth of the fault. It looks similar to the graph below.
![IMG_1977](https://github.com/user-attachments/assets/ecc833c4-b8c2-4b2e-ac06-2b6c0a3fb6b7)


Thanks,
Luke

**Comment by x3zou** [comment]
For now, our code can't achieve that automatically. You might be able to do it by manually manipulating the output of **load_fault_one_plane()**

**Comment by bad-guyluke** [comment]
Hello,
OK. I will try to do it. Thank you for your patience and guidance!
