### ISSUE TITLE
Program running system

### ISSUE THREAD

**Issue by shanqiang-mouse** [ZeyuJin/geodetic_inversion#3]
Hi. I would like to ask you a question. when I run this code in matlab of linux system, there is an error in "system(['gmt grdsample ',filepath,'/' input_grid,interval,' -G', filepath,'/' output_grid])", and the output is that "gmt: /usr/local/MATLAB/R2018a/bin/glnxa64/libtiff.so.5: no version information available (required by /usr/lib/libgdal.so.20)". Do you know the solution? Thank you very much for your kind consideration and I am looking forward to your reply.

**Comment by ZeyuJin** [comment]
Hi, I think this issue was due to your GMT libs are not properly installed in your local environment. 
GMT is dependent on GDAL and TIFF. You need to install all GMT libraries and make sure GMT can be run successfully in your local environment first.
