### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by canqinjingxin** [ZeyuJin/geodetic_inversion#5]
Hello, thank you very much for the code. I have also successfully calculated the results with the example you provided. However, when I replace the part of the Green's function in the code with my own model (poroelastic), I never get the proper finite fault model results. Therefore I would like to ask you what could be the reason for this?

And also I would like to ask you which earthquake is the InSAR data given in the example? 

Thank you very much and looking forward to your reply!

![ce92032fc3d6e17496dfaebcbfe19f7](https://github.com/ZeyuJin/geodetic_inversion/assets/92517550/d8a2fa4e-f5b2-4323-86b7-0bedb2d4e0dd)

And this is the result of my inversion(south is positive).

**Comment by x3zou** [comment]
Hello,
  Could you please describe how exactly you replaced the Green's function (how you modified the code)?
  
  This earthquake is 2015 the M 7.2 Sarez (Pamir) earthquake.

**Comment by canqinjingxin** [comment]
Thank you very much for your reply, the code description is relatively complex, I have sent the relevant code to your email, thank you for your guidance!
