### ISSUE TITLE
Undefined function 'depth_dependent_point' in main_interpolate.m

### ISSUE THREAD

**Issue by Suen2023** [ZeyuJin/geodetic_inversion#7]
I am trying to create 3D fault geometry using the _main_interpolate.m_ script from the _curveFaultGeometry_ package. It seems that the _depth_dependent_point_ function is missing. I am not sure if this function is integrated into GMTSAR or other packages. Can you share a copy with me?
![issue](https://github.com/ZeyuJin/geodetic_inversion/assets/171203476/49845798-23d0-43bb-96fc-c7898ffe61f0)

**Comment by ZeyuJin** [comment]
Hi Kai,

I just add "depth_dependent_point.m" into the directory "geometry/curveFault".
Please let us know if you have more questions.

Cheers,
Zeyu
