### ISSUE TITLE
How to jointly invert coseismic slip models using GNSS and InSAR?

### ISSUE THREAD

**Issue by lightwjq** [ZeyuJin/geodetic_inversion#8]
The example program you provided only used InSAR data for inversion. If I want to incorporate GNSS data as constraints, what should I pay attention to, and should the units of the GNSS data be in meters or centimeters?

**Comment by x3zou** [comment]
Hello,

  It is simple to include GNSS data and you can adjust the inversion function ('make_fault_from_insar.m') by adding a few lines.
 
  There is an example at inversion/make_fault_from_insar_new.m. In line 13, a GNSS data weight is provided; in line 105, a Green's function is built upon the GNSS data; In line 216, a forward model for GNSS data is calculated (this is only for plotting); In lines 134-147, all the Green's function and raw data are concatenated. You can add more than one GNSS data by replicating those lines.

  Input GNSS deformation should be cm by default, but you can change it as long as the unit is the same as the InSAR data. Just be careful with the unit of color bar when you plot them out.

  Let me know if you need more help! 

Thanks,
Xiaoyu

**Comment by lightwjq** [comment]
Dear Dr. Zou

    Thank you for your detailed reply! This has resolved most of my doubts. In addition, what should the data format of GPS files be like, and is it consistent with the InSAR data format?

     Thank you for your time and consideration!

Best regards,
Jingqi Wang

**Comment by x3zou** [comment]
Hi Jingqi
  
  I'm glad that you found it helpful! I uploaded a sample GPS data to the example directory. You can find it at WorkExample/GPS/GPS.mat.
