### ISSUE TITLE
questions for parameters

### ISSUE THREAD

**Issue by canqinjingxin** [ZeyuJin/geodetic_inversion#9]
Hello, Dr. Jin, I would like to ask  what values of the lame constants (λ and μ) you used in the calculation of the Green's function in pamir earthquake, I have only seen the Poisson's ratio in your article. I hope to get your answer, extremely grateful.

**Comment by x3zou** [comment]
Hello,

  Only Poisson's ratio is needed to calculate the Green's function. You can check out the calc_green_insar_okada.m in the OtherFunc directory for the Green's function calculation process.

Xiaoyu

**Comment by canqinjingxin** [comment]
Thank you very much for your instruction. Practically I am doing research on poroelastic and I would like to get some advice on the rock background of the Pamir earthquake, such as what is the composition of the rock, which is used to calculate the various parameters of the poroelastic

**Comment by x3zou** [comment]
Sorry, I'm not familiar with the precise rock backgrounds. I will get back to you once I get a good answer. But I suggest that you could do a literature search on that topic. There should be some papers about it.

**Comment by canqinjingxin** [comment]
Thank you very much for your guidance and good luck with your research!
